name: Publish Extension

on:
  push:
    tags:
      - 'v*' # O pipeline será disparado quando você criar uma tag (ex: v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # 1. Verificação de Lint (Erros de padronização e sintaxe)
      - name: Run Lint
        run: npm run lint

      # 2. Verificação de Compilação
      - name: Compile Extension
        run: npm run compile

      # 3. Execução de Testes
      # O xvfb-run é necessário para simular um display para o VS Code abrir nos testes
      - name: Run Tests
        run: xvfb-run -a npm test

      # 4. Publicação (Só será executada se todas as etapas acima passarem)
      - name: Publish to Marketplace
        if: success()
        run: npx @vscode/vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}